inherit_gem:
  gnar-style:
    - rubocop/rubocop_gem.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 120
  Severity: refactor

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Max: 15
  IgnoredMethods:
    - test_greek_to_beta_code
    - test_beta_code_to_greek

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
